- Dr Thomas Hall
- Dr Matthew Campbell (Matt)
- Dr Joshua Hill (Joss)
- Dr Joseph Mitchell (Joe)
- Dr James Powell (Jamie)
- Dr Samuel Russell (Rush)
- Dr Daniel Patel (Dan)
- Dr Alexander Bell (Alek)
- Dr Luke Marshall (Marsh)
- Dr Benjamin Hull (Ben)