#!/usr/bin/env ruby

require "bundler/setup"
require "tty-prompt"
require "colorize"
require "yaml"
require 'optparse'

banner = %Q(
                                                                                     ,---,  
                                                                                  ,`--.' |  
  .--.--.       ___                                                               |   :  :  
 /  /    '.   ,--.'|_                                ,---,              ,-.----.  '   '  ;  
|  :  /`. /   |  | :,'                   ,---,     ,---.'|         ,--, \    /  \ |   |  |  
;  |  |--`    :  : ' :               ,-+-. /  |    |   | :       ,'_ /| |   :    |'   :  ;  
|  :  ;_    .;__,'  /    ,--.--.    ,--.'|'   |    |   | |  .--. |  | : |   | .\ :|   |  '  
 \  \    `. |  |   |    /       \  |   |  ,"' |  ,--.__| |,'_ /| :  . | .   : |: |'   :  |  
  `----.   \:__,'| :   .--.  .-. | |   | /  | | /   ,'   ||  ' | |  . . |   |  \ :;   |  ;  
  __ \  \  |  '  : |__  \__\/: . . |   | |  | |.   '  /  ||  | ' |  | | |   : .  |`---'. |  
 /  /`--'  /  |  | '.'| ," .--.; | |   | |  |/ '   ; |:  |:  | : ;  ; | :     |`-' `--..`;  
'--'.     /   ;  :    ;/  /  ,.  | |   | |--'  |   | '/  ''  :  `--'   \:   : :   .--,_     
  `--'---'    |  ,   /;  :   .'   \|   |/      |   :    :|:  ,      .-./|   | :   |    |`.  
               ---`-' |  ,     .-./'---'        \   \  /   `--`----'    `---'.|   `-- -`, ; 
                       `--`---'                  `----'                   `---`     '---`"  
).colorize(:yellow)

puts banner

options = {
  file: ENV['HOME']+"/standup.yml"
}

options_parser = OptionParser.new do |opts|
                  opts.banner = "Usage: standup [options]"

                  opts.on("-f", "--file FILE", "File path with Participants") do |f|
                    options[:file] = f
                  end
                  opts.on("-i", "--interactive", "Interactive mode: exclude participants at the begining") do |f|
                    options[:interactive] = f
                  end
                  opts.on("-h", "--help", "Prints help") do
                    puts opts
                    exit
                  end
                end

begin
  options_parser.parse!(ARGV)
rescue OptionParser::ParseError
  puts "Error: invalid option"
  puts options_parser
  exit 1
end

begin
  data = File.read(options[:file])
rescue
  puts ""
  puts "[Missing config file] Default location is `~/standup.yml` but you can run it with flag `-f`"
  puts "with a path to a your config file."
  puts ""
  puts options_parser
  exit 1
end

begin
  employees = YAML.load(data).sort
rescue
  puts "Error: Invalid file"
  puts "Example file content:"
  puts %Q(
- Dr Thomas Hall
- Dr Matthew Campbell (Matt)
- Dr Joshua Hill (Joss)
- Dr Joseph Mitchell (Joe)
- Dr James Powell (Jamie)
- Dr Samuel Russell (Rush)
  )
  exit 1
end

assisting = employees.dup
prompt = TTY::Prompt.new

if options[:interactive]
  o = prompt.multi_select("Exclude not present".colorize(:red), employees, per_page: employees.count)
  o.each { |n| assisting.delete(n) }
end

prompt.multi_select("Start ->".colorize(:yellow), assisting, per_page: assisting.count)

puts "==========================================================================================".colorize(:yellow)

