#!/usr/bin/env ruby

require "bundler/setup"
require "standup"
require "tty-prompt"
require "colorize"
require "yaml"

puts %Q(
                                                                                     ,---,  
                                                                                  ,`--.' |  
  .--.--.       ___                                                               |   :  :  
 /  /    '.   ,--.'|_                                ,---,              ,-.----.  '   '  ;  
|  :  /`. /   |  | :,'                   ,---,     ,---.'|         ,--, \    /  \ |   |  |  
;  |  |--`    :  : ' :               ,-+-. /  |    |   | :       ,'_ /| |   :    |'   :  ;  
|  :  ;_    .;__,'  /    ,--.--.    ,--.'|'   |    |   | |  .--. |  | : |   | .\ :|   |  '  
 \  \    `. |  |   |    /       \  |   |  ,"' |  ,--.__| |,'_ /| :  . | .   : |: |'   :  |  
  `----.   \:__,'| :   .--.  .-. | |   | /  | | /   ,'   ||  ' | |  . . |   |  \ :;   |  ;  
  __ \  \  |  '  : |__  \__\/: . . |   | |  | |.   '  /  ||  | ' |  | | |   : .  |`---'. |  
 /  /`--'  /  |  | '.'| ," .--.; | |   | |  |/ '   ; |:  |:  | : ;  ; | :     |`-' `--..`;  
'--'.     /   ;  :    ;/  /  ,.  | |   | |--'  |   | '/  ''  :  `--'   \:   : :   .--,_     
  `--'---'    |  ,   /;  :   .'   \|   |/      |   :    :|:  ,      .-./|   | :   |    |`.  
               ---`-' |  ,     .-./'---'        \   \  /   `--`----'    `---'.|   `-- -`, ; 
                       `--`---'                  `----'                   `---`     '---`"  
).colorize(:color => :yellow)

puts ""
puts ""

begin
  data = File.read(ENV['HOME']+"/standup.yml")
  employees = YAML.load(data).sort
rescue
  puts "Please add file `standup.yml` in your home directory"
  exit 1
end

assisting = employees.dup
prompt = TTY::Prompt.new

o = prompt.multi_select("Select not present".colorize(:yellow), employees, per_page: employees.count)

o.each { |n| assisting.delete(n) }

prompt.multi_select("Mark while they talk".colorize(:yellow), assisting, per_page: assisting.count)

puts "==========================================================================================".colorize(:yellow)

