#!/usr/bin/env ruby

require "bundler/setup"
require "standup"
require "tty-prompt"

employees = [
  "Adrian",
  "Alex",
  "Anna",
  "Artur",
  "Cesc",
  "David",
  "Josele",
  "Julia",
  "Ksenia",
  "Laia",
  "Manu",
  "Marc",
  "Samu",
  "Victor"
]

assist = employees.dup
prompt = TTY::Prompt.new

o = prompt.multi_select("not present?", employees, per_page: employees.count)

o.each { |n| assist.delete(n) }

prompt.multi_select("How has talked?", assist, per_page: assist.count)

puts "Boom!!"

